MEDIT_MAXLINES=10
export MEDIT_MAXLINES
echo $MEDIT_MAXLINES
MEDIT_MAXCOLUMNS=30
export MEDIT_MAXCOLUMNS
echo $MEDIT_MAXCOLUMNS
MEDIT_TIMEOUT=20
export MEDIT_TIMEOUT
echo $MEDIT_TIMEOUT
MEDIT_MAXUSERS=12
export MEDIT_MAXUSERS
echo $MEDIT_MAXUSERS
